words = [
	"arktype",
	"bundler",
	"codestral",
	"consola",
	"esm",
	"ianitor",
	"ide",
	"iex",
	"irm",
	"jsr",
	"knip",
	"oxc",
	"oxfmt",
	"oxfmtrc",
	"oxlint",
	"oxlintrc",
	"picocolors",
	"profilebegin",
	"profileend",
	"rbxts",
	"tsc",
	"tsgo",
	"tsgolint",
	"typebox",
	"unmemoized",
	"vfc",
	"vscode",
	"vtbot",
	"vtsls",
	"zprofile",
	"zshenv",
]
