export { definePlugin } from "./define-plugin";
export { defineRule } from "./define-rule";

export type {
	Context,
	CreateOnceRule,
	CreateRule,
	Diagnostic,
	InferContextFromRule,
	Plugin,
	Rule,
	RuleMeta,
	RuleOptions,
} from "./types";

export type {
	AfterHook,
	BeforeHook,
	BooleanToken,
	Comment,
	CountOptions,
	Definition,
	DefinitionType,
	DiagnosticData,
	Envs,
	ESTree,
	FilterFn,
	FilterFn as FilterFunction,
	Fix,
	Fixer,
	FixFn,
	FixFn as FixFunction,
	Globals,
	IdentifierToken,
	JSXIdentifierToken,
	JSXTextToken,
	KeywordToken,
	LanguageOptions,
	Context as LegacyContext,
	CreateOnceRule as LegacyCreateOnceRule,
	CreateRule as LegacyCreateRule,
	Diagnostic as LegacyDiagnostic,
	Plugin as LegacyPlugin,
	Rule as LegacyRule,
	RuleMeta as LegacyRuleMeta,
	LineColumn,
	Location,
	Node,
	NullToken,
	NumericToken,
	Options,
	PrivateIdentifierToken,
	PunctuatorToken,
	Range,
	Ranged,
	RangeOptions,
	Reference,
	RegularExpressionToken,
	RuleDeprecatedInfo,
	RuleDocs,
	RuleOptionsSchema,
	RuleReplacedByExternalSpecifier,
	RuleReplacedByInfo,
	Scope,
	ScopeManager,
	ScopeType,
	Settings,
	SkipOptions,
	SourceCode,
	Span,
	StringToken,
	Suggestion,
	TemplateToken,
	Token,
	Variable,
	Visitor,
	VisitorWithHooks,
} from "@oxlint/plugins";
