name: ci

on:
  push:
    branches:
      - main
    paths:
      - "src/**/*.ts"
      - "tests/**/*.ts"
      - "scripts/**/*.ts"
      - ".github/actions/**/*.yaml"
      - "package.json"
      - "aube-lock.yaml"
      - "aube-workspace.yaml"
      - "mise.lock"
      - "mise.toml"
      - "knip.ts"
      - "tsconfig*.json"
      - "vitest.config.ts"
      - ".oxlintrc.json"
      - "biome.jsonc"
  pull_request:
    paths:
      - "src/**/*.ts"
      - "tests/**/*.ts"
      - "scripts/**/*.ts"
      - ".github/actions/**/*.yaml"
      - "package.json"
      - "aube-lock.yaml"
      - "aube-workspace.yaml"
      - "mise.lock"
      - "mise.toml"
      - "knip.ts"
      - "tsconfig*.json"
      - "vitest.config.ts"
      - ".oxlintrc.json"
      - "biome.jsonc"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup build environment
        uses: ./.github/actions/setup

      - name: Validate package
        uses: ./.github/actions/validate-package
        with:
          check-biome: "true"
          check-knip: "true"
          lint-command: aube run oxc .

      - name: Tests
        run: aube run test
